include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    use_key_in_widget_constructors: false
    curly_braces_in_flow_control_structures: false
    require_trailing_commas: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
