name: mega_form
description: "Mega Form"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.1

dependencies:
  flutter:
    sdk: flutter

  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0

  pad5:
    git:
      url: https://github.com/z80maniac/pad5.git
      ref: 1a4fd401ba790abf842692ee67e8aec9cae9c301

dev_dependencies:
  flutter_lints: ^6.0.0
